#BUILDER#

FROM python:3.9.6-alpine as builder

WORKDIR /usr/src/app


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev


RUN pip install --upgrade pip
RUN pip install flake8=3.9.2

COPY . .

RUN flake8 --ignore=E501,F401 .

COPY ./req.txt

RUN  pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r req.txt
